### ISSUE TITLE
First run!

### ISSUE THREAD

**Issue by cbo317110** [cbo317110/db-mirror#1]
Always considering errors!
- [x] create file `db-mirror.php`
- [x] require laravel database tool
- [x] setup connection
- [x] read/write yaml files
- [x] put connection info in a yaml file
- [x] test connection
- [x] create a folder called `tables` on root app folder
- [x] create a file called `books.yml` inside `tables` folder with this body
```yaml
id: true
title: string
category_id: integer
```
- [x] create a file called `categories.yml` inside `tables` folder with this body
```yaml
id: true
name: string
```
- [x] read files from tables folder
- [x] check if table `{filename}` exists
- [x] if table don't exists create it with a incremental id
- [x] loop through columns and
  - [x]  if they don't exist create it
 - [x] create a folder called `relationships` on root app folder
 - [x] create a file called `book_category` on root app folder
```yaml
from: books
to: categories
with: categories_id
```
- [x] read files from `relationships` folder
- [x] setup a foreign key with file body, considering error
